import * as PDFDocument from 'pdfkit';

export async function generateInvoicePdfBuffer(invoice: any, company: any): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', (err) => reject(err));

    const primaryColor = '#003d9b';
    const secondaryColor = '#434654';

    // Header Background
    doc.rect(0, 0, 612, 100).fill(primaryColor);
    
    // Branding
    doc.fillColor('#FFFFFF').fontSize(24).font('Helvetica-Bold').text(company.name || 'Karobar SaaS', 50, 30);
    doc.fontSize(10).font('Helvetica').text(company.address || 'Business Address Here', 50, 60);
    doc.text(`Phone: ${company.phone || '+92 000 0000'}`, 50, 75);

    doc.fontSize(30).font('Helvetica-Bold').text('INVOICE', 400, 40, { align: 'right' });

    // Move down for billing info
    doc.moveDown(5);
    doc.fillColor('#000000').fontSize(12).font('Helvetica-Bold').text('BILL TO:', 50, 130);
    doc.fontSize(11).font('Helvetica').text(invoice.customer?.name || 'Guest Customer', 50, 150);
    doc.fontSize(10).fillColor(secondaryColor).text(invoice.customer?.address || 'N/A', 50, 165, { width: 250 });
    doc.text(`Email: ${invoice.customer?.email || 'N/A'}`, 50, 195);

    // Invoice Meta
    doc.fillColor('#000000').fontSize(10).font('Helvetica-Bold').text('Invoice #:', 400, 130);
    doc.font('Helvetica').text(invoice.invoiceNumber, 480, 130);
    
    doc.font('Helvetica-Bold').text('Date:', 400, 145);
    doc.font('Helvetica').text(new Date(invoice.issueDate).toLocaleDateString(), 480, 145);

    doc.font('Helvetica-Bold').text('Due Date:', 400, 160);
    doc.font('Helvetica').text(new Date(invoice.dueDate).toLocaleDateString(), 480, 160);

    doc.font('Helvetica-Bold').text('Status:', 400, 175);
    doc.font('Helvetica').text(invoice.status, 480, 175);

    // Table Header
    const tableTop = 230;
    doc.rect(50, tableTop, 500, 20).fill(primaryColor);
    doc.fillColor('#FFFFFF').fontSize(10).font('Helvetica-Bold');
    doc.text('#', 60, tableTop + 5);
    doc.text('Description', 100, tableTop + 5);
    doc.text('Qty', 300, tableTop + 5, { width: 40, align: 'right' });
    doc.text('Price', 350, tableTop + 5, { width: 80, align: 'right' });
    doc.text('Total', 450, tableTop + 5, { width: 90, align: 'right' });

    // Table Rows
    let rowY = tableTop + 25;
    doc.fillColor('#333333').font('Helvetica');
    
    (invoice.items || []).forEach((item, i) => {
      // Draw zebra striping
      if (i % 2 === 1) {
        doc.rect(50, rowY - 2, 500, 15).fill('#F9FAFB');
        doc.fillColor('#333333');
      }

      doc.text(i + 1, 60, rowY);
      doc.text(item.description, 100, rowY, { width: 180 });
      doc.text(item.quantity, 300, rowY, { width: 40, align: 'right' });
      doc.text(parseFloat(item.unitPrice).toLocaleString(), 350, rowY, { width: 80, align: 'right' });
      doc.text(parseFloat(item.totalAmount).toLocaleString(), 450, rowY, { width: 90, align: 'right' });
      
      rowY += 18;
    });

    // Summary
    const summaryY = rowY + 20;
    doc.moveTo(350, summaryY).lineTo(550, summaryY).stroke('#EEEEEE');
    
    doc.fontSize(10).font('Helvetica-Bold').text('Subtotal:', 350, summaryY + 10);
    doc.font('Helvetica').text(`Rs ${parseFloat(invoice.subTotal).toLocaleString()}`, 450, summaryY + 10, { width: 90, align: 'right' });

    doc.font('Helvetica-Bold').text('Tax:', 350, summaryY + 25);
    doc.font('Helvetica').text(`Rs ${parseFloat(invoice.taxAmount).toLocaleString()}`, 450, summaryY + 25, { width: 90, align: 'right' });

    if (parseFloat(invoice.discountAmount) > 0) {
      doc.font('Helvetica-Bold').text('Discount:', 350, summaryY + 40);
      doc.font('Helvetica').text(`-Rs ${parseFloat(invoice.discountAmount).toLocaleString()}`, 450, summaryY + 40, { width: 90, align: 'right' });
    }

    // Final Total
    const totalBoxY = summaryY + 60;
    doc.rect(350, totalBoxY, 200, 25).fill(primaryColor);
    doc.fillColor('#FFFFFF').fontSize(12).font('Helvetica-Bold').text('TOTAL:', 365, totalBoxY + 7);
    doc.text(`Rs ${parseFloat(invoice.totalAmount).toLocaleString()}`, 450, totalBoxY + 7, { width: 90, align: 'right' });

    // Footer
    doc.fillColor('#999999').fontSize(8).text('Thank you for your business!', 0, 780, { align: 'center' });
    doc.text(`Generated by Karobar SaaS on ${new Date().toLocaleString()}`, 0, 792, { align: 'center' });

    doc.end();
  });
}
